spring:
  application:
   name: service-ribbon-hystrix
server:
  port: 8768
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000